trace-log:
  feign-okhttp:
    enable: true
  rest-template:
    enable: true
  cut-point:
    enable: true
    expression: "execution(* com.lei.controller.SampleController.*(..))"
#execution(* com..*.*Controller.*(..))